spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

billing:
  cron: "0 0 9 * * *"
  interval-days: 30
  retry-interval-days: 3

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
